In [1]:
from task4 import *
from task3 import *
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.transforms import ToPILImage
import matplotlib.pyplot as plt

(225, 225)
(225, 225)
(225, 225)
(225, 225)
151875
[[[0.         0.         0.        ]
  [0.01960784 0.01960784 0.01960784]
  [0.02745098 0.02745098 0.02745098]
  ...
  [0.29411766 0.3372549  0.25882354]
  [0.28235295 0.32941177 0.24313726]
  [0.25882354 0.30588236 0.23921569]]

 [[0.         0.         0.        ]
  [0.01960784 0.01960784 0.01960784]
  [0.04705882 0.04705882 0.04705882]
  ...
  [0.3019608  0.3529412  0.2627451 ]
  [0.3137255  0.36862746 0.2784314 ]
  [0.45882353 0.5176471  0.43137255]]

 [[0.         0.         0.        ]
  [0.04705882 0.04705882 0.04705882]
  [0.0627451  0.0627451  0.0627451 ]
  ...
  [0.4392157  0.49411765 0.4117647 ]
  [0.4627451  0.52156866 0.44705883]
  [0.4        0.45490196 0.39215687]]

 ...

 [[0.28235295 0.29411766 0.3254902 ]
  [0.2784314  0.2901961  0.3254902 ]
  [0.25882354 0.27058825 0.30588236]
  ...
  [0.40784314 0.41568628 0.4745098 ]
  [0.44313726 0.4509804  0.50980395]
  [0.46666667 0.4745098  0.5372549 ]]

 [[0.28627452 0.2980392

In [2]:
train_dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transforms.ToTensor())
test_dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transforms.ToTensor())

transform_pipeline_1 = Compose([
    RandomCrop(p=0.7, crop_size=(24, 24)),
    RandomRotate(p=0.6, degrees=30),
    RandomZoom(p=0.5, zoom_range=(0.8, 1.2)),
    ToTensor()
])

transform_pipeline_2 = Compose([
    RandomCrop(p=0.9, crop_size=(26, 26)),
    RandomRotate(p=0.9, degrees=40),
    RandomZoom(p=0.8, zoom_range=(0.7, 1.3)),
    ToTensor()
])

transform_pipeline_none = Compose([ToTensor()])

train_dataset_with_transforms_1 = FashionMNISTDatasetWithTransforms(train_dataset, transforms=transform_pipeline_1)
train_dataset_with_transforms_2 = FashionMNISTDatasetWithTransforms(train_dataset, transforms=transform_pipeline_2)
train_dataset_no_transforms = FashionMNISTDatasetWithTransforms(train_dataset, transforms=transform_pipeline_none)

train_loader_1 = DataLoader(train_dataset_with_transforms_1, batch_size=64, shuffle=True)
train_loader_2 = DataLoader(train_dataset_with_transforms_2, batch_size=64, shuffle=True)
train_loader_no_transforms = DataLoader(train_dataset_no_transforms, batch_size=64, shuffle=True)
test_loader = DataLoader(FashionMNISTDatasetWithTransforms(test_dataset, transforms=transform_pipeline_none),
                         batch_size=64, shuffle=False)

model_1 = SimpleCNN()
model_2 = SimpleCNN()
model_no_transforms = SimpleCNN()

criterion = nn.CrossEntropyLoss()
optimizer_1 = optim.Adam(model_1.parameters(), lr=0.001)
optimizer_2 = optim.Adam(model_2.parameters(), lr=0.001)
optimizer_no_transforms = optim.Adam(model_no_transforms.parameters(), lr=0.001)

num_epochs = 20

print("Training with Transform Pipeline 1:")
train_loss_1, train_acc_1 = train_model(model_1, train_loader_1, criterion, optimizer_1, num_epochs)
test_loss_1, test_acc_1 = test_model(model_1, test_loader, criterion)

print("\nTraining with Transform Pipeline 2:")
train_loss_2, train_acc_2 = train_model(model_2, train_loader_2, criterion, optimizer_2, num_epochs)
test_loss_2, test_acc_2 = test_model(model_2, test_loader, criterion)

print("\nTraining with No Transforms:")
train_loss_no, train_acc_no = train_model(model_no_transforms, train_loader_no_transforms, criterion,
                                          optimizer_no_transforms, num_epochs)
test_loss_no, test_acc_no = test_model(model_no_transforms, test_loader, criterion)

plot_metrics(train_loss_1, train_acc_1, test_loss_1, test_acc_1, title_suffix="(Transform Pipeline 1)")
plot_metrics(train_loss_2, train_acc_2, test_loss_2, test_acc_2, title_suffix="(Transform Pipeline 2)")
plot_metrics(train_loss_no, train_acc_no, test_loss_no, test_acc_no, title_suffix="(No Transforms)")


Training with Transform Pipeline 1:
(28, 28)


AttributeError: 'RandomCrop' object has no attribute 'size'